### ISSUE TITLE
Can't use .exe files

### ISSUE THREAD

**Issue by MKKelvinHK** [THEMIO90000/Adobe-Discord-RPC#2]
Yeah, i know this maybe a bit old in 2020 but this is show up when i try to use it in 2020
![image](https://user-images.githubusercontent.com/42489566/81880572-6640be80-95c0-11ea-9ef0-38f4fe1a69d2.png)

**Comment by Euxaty** [comment]
For me too, you can't fix it. He needs to redo it.

**Comment by InspecteurKepler** [comment]
I'll work on that. Thanks to have reported this problem !

**Comment by Lunyyx** [comment]
> I'll work on that. Thanks to have reported this problem !

Credits for me if it's fixed :3

**Comment by InspecteurKepler** [comment]
> > I'll work on that. Thanks to have reported this problem !
> 
> Credits for me if it's fixed :3

Yes x)
